(function(){
var k=this;function l(a,b){var c=a.split("."),d=k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var f;c.length&&(f=c.shift());)c.length||void 0===b?d=d[f]?d[f]:d[f]={}:d[f]=b}
function m(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function n(a){var b=m(a);return"array"==b||"object"==b&&"number"==typeof a.length}function p(a){return"string"==typeof a}function q(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function r(a,b,c){return a.call.apply(a.bind,arguments)}
function u(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function v(a,b,c){v=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?r:u;return v.apply(null,arguments)}
Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return v.apply(null,c)}return v(this,a)};var w=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function x(a){if(!y.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(z,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(A,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(B,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(C,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(D,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(E,"&#0;"));return a}var z=/&/g,A=/</g,B=/>/g,C=/"/g,D=/'/g,E=/\x00/g,y=/[\x00&<>"']/;
function F(a){return Array.prototype.join.call(arguments,"")}function G(a,b){return a<b?-1:a>b?1:0}function aa(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};var H=Array.prototype,ba=H.indexOf?function(a,b,c){return H.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(p(a))return p(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},I=H.forEach?function(a,b,c){H.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=p(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)};function ca(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var J;a:{var K=k.navigator;if(K){var L=K.userAgent;if(L){J=L;break a}}J=""};function M(a,b){for(var c in a)b.call(void 0,a[c],c,a)}var N="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function da(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<N.length;e++)c=N[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var ea=-1!=J.indexOf("Opera")||-1!=J.indexOf("OPR"),O=-1!=J.indexOf("Trident")||-1!=J.indexOf("MSIE"),P=-1!=J.indexOf("Gecko")&&-1==J.toLowerCase().indexOf("webkit")&&!(-1!=J.indexOf("Trident")||-1!=J.indexOf("MSIE")),fa=-1!=J.toLowerCase().indexOf("webkit");function Q(){var a=k.document;return a?a.documentMode:void 0}
var R=function(){var a="",b;if(ea&&k.opera)return a=k.opera.version,"function"==m(a)?a():a;P?b=/rv\:([^\);]+)(\)|;)/:O?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:fa&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(J))?a[1]:"");return O&&(b=Q(),b>parseFloat(a))?String(b):a}(),S={};
function T(a){if(!S[a]){for(var b=0,c=w(String(R)).split("."),d=w(String(a)).split("."),f=Math.max(c.length,d.length),e=0;0==b&&e<f;e++){var g=c[e]||"",h=d[e]||"",ga=RegExp("(\\d*)(\\D*)","g"),ha=RegExp("(\\d*)(\\D*)","g");do{var s=ga.exec(g)||["","",""],t=ha.exec(h)||["","",""];if(0==s[0].length&&0==t[0].length)break;b=G(0==s[1].length?0:parseInt(s[1],10),0==t[1].length?0:parseInt(t[1],10))||G(0==s[2].length,0==t[2].length)||G(s[2],t[2])}while(0==b)}S[a]=0<=b}}
var U=k.document,V=U&&O?Q()||("CSS1Compat"==U.compatMode?parseInt(R,10):5):void 0;var ia=!O||O&&9<=V;!P&&!O||O&&O&&9<=V||P&&T("1.9.1");O&&T("9");function ja(a){var b,c,d,f;b=document;if(b.querySelectorAll&&b.querySelector&&a)return b.querySelectorAll(""+(a?"."+a:""));if(a&&b.getElementsByClassName){var e=b.getElementsByClassName(a);return e}e=b.getElementsByTagName("*");if(a){f={};for(c=d=0;b=e[c];c++){var g=b.className,h;if(h="function"==typeof g.split)h=0<=ba(g.split(/\s+/),a);h&&(f[d++]=b)}f.length=d;return f}return e}
function ka(a,b){M(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in W?a.setAttribute(W[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var W={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function la(a,b,c){var d=arguments,f=document,e=d[0],g=d[1];if(!ia&&g&&(g.name||g.type)){e=["<",e];g.name&&e.push(' name="',x(g.name),'"');if(g.type){e.push(' type="',x(g.type),'"');var h={};da(h,g);delete h.type;g=h}e.push(">");e=e.join("")}e=f.createElement(e);g&&(p(g)?e.className=g:"array"==m(g)?e.className=g.join(" "):ka(e,g));2<d.length&&ma(f,e,d);return e}
function ma(a,b,c){function d(c){c&&b.appendChild(p(c)?a.createTextNode(c):c)}for(var f=2;f<c.length;f++){var e=c[f];if(!n(e)||q(e)&&0<e.nodeType)d(e);else{var g;a:{if(e&&"number"==typeof e.length){if(q(e)){g="function"==typeof e.item||"string"==typeof e.item;break a}if("function"==m(e)){g="function"==typeof e.item;break a}}g=!1}I(g?ca(e):e,d)}}}function na(a){return oa(a,function(a){if(a="A"==a.nodeName)a=!0;return a})}
function oa(a,b){for(var c=0;a;){if(b(a))return a;a=a.parentNode;c++}return null};function pa(a){if(a.dataset)return a.dataset;var b={};a=a.attributes;for(var c=0;c<a.length;++c){var d=a[c];if(0==d.name.lastIndexOf("data-",0)){var f=aa(d.name.substr(5));b[f]=d.value}}return b};function X(a,b){this.g=a;this.c=b;this.src=b.src;this.type=b.type;this.b=b.cat}function Y(a,b){switch(a){case "floodlight":var c=1E13*(Math.random()+""),d="";M(b,function(a,f){if("ord"==f){var h=x(b.ord);c="1"==h?h+";num="+c:h}else h=x(f)+"="+x(a)+";",d+=h});var f=la("iframe",{src:F("//",b.src,".fls.doubleclick.net/activityi;",d,"ord=",c,"?"),width:1,height:1,style:"display: none;"});document.body.appendChild(f)}}
X.prototype.a=function(a,b){var c=document;a=p(a)?c.getElementById(a):a;1==a.nodeType&&"A"==a.tagName&&b?Z(a,this.f,this):Z(a,this.d,this)};X.prototype.d=function(a){a=a||window.event;this.track($(this,a.currentTarget||a.srcElement))};X.prototype.track=function(a){Y(this.g,a||this.c)};
X.prototype.f=function(a){a=a||window.event;var b=a.currentTarget||a.srcElement;this.track($(this,b));"A"!=b.tagName&&(b=na(b));a&&"click"==a.type&&b&&b.href&&"_blank"!=b.target&&(a.preventDefault?a.preventDefault():a.returnValue=!1,setTimeout(function(){window.top.location=b.href},1E3))};X.prototype.e=function(a,b){var c=ja(a);I(c,function(a){this.a(a,b)},this)};
function $(a,b){var c=pa(b),d={};d.src=c.dSrc||a.src;d.cat=c.dCat||a.b;d.type=c.dType||a.type;M(c,function(a,b){var c=b.match(/^d([A-Z])(\w+)$/);c&&(b=c[1].toLowerCase()+c[2],d[b]=a)});return d}function Z(a,b,c){c&&(b=v(b,c));a.addEventListener?a.addEventListener("click",b,!1):a.attachEvent&&a.attachEvent("onclick",b)}l("gweb.analytics.DoubleTrack",X);l("gweb.analytics.DoubleTrack.track",Y);X.prototype.track=X.prototype.track;X.prototype.trackClass=X.prototype.e;X.prototype.trackElement=X.prototype.a;
})()